# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e103e3b43b8023bdbdb673ee18a3f202520d9e6aab4b0967b55574fdcd1b33f3dff7c705c6151a57a06e87a8a2837f7e0dd5ebd25d4a41952a9cc54dc1942566
  s3_host_name: <%= ENV['S3_HOST_NAME'] %>
  bucket: <%= ENV['BUCKET'] %>
  access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: 66133bd580cb04d27dc49fcc700c9a67f51fbf5563ac16d09db2e7c7f26d261ac7e2964e553d346b12167f68c95bb2a492c48aa368a24466ac18c90267cff62e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_host_name: <%= ENV['S3_HOST_NAME'] %>
  bucket: <%= ENV['BUCKET'] %>
  access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>